# Use an official Node.js image
FROM node:18

# Set working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY ./frontend/package*.json ./
RUN npm install

# Copy the rest of the application code
COPY ./frontend .

# Expose port 3000 and start the Next.js development server
EXPOSE 3000
CMD ["npm", "run", "dev"]
